[package]
name = "jsonwebkey"
version = "0.3.4"
authors = ["Nick Hynes <nhynes@nhynes.com>"]
description = "JSON Web Key (JWK) (de)serialization, generation, and conversion."
readme = "README.md"
repository = "https://github.com/nhynes/jwk-rs"
documentation = "http://docs.rs/jsonwebkey/"
license = "MIT"
edition = "2018"

[dependencies]
base64        = "0.13"
bitflags      = "1.2"
generic-array = "0.14"
jsonwebtoken  = { version = "7.2", optional = true }
num-bigint    = { version = "0.4", optional = true }
p256          = { version = "0.9", optional = true, features = ["arithmetic"] }
rand          = { version = "0.8", optional = true }
serde         = { version = "1.0", features = ["derive"] }
serde_json    = "1.0"
thiserror     = "1.0"
yasna         = { version = "0.4", optional = true, features = ["num-bigint"] }
zeroize       = { version = "1.4", features = ["zeroize_derive"] }

[features]
pkcs-convert = ["num-bigint", "yasna"]
#jwt-convert  = ["pkcs-convert", "jsonwebtoken"]
jwt-convert  = ["pkcs-convert"]
generate     = ["p256", "rand"]

[dev-dependencies]
#jsonwebtoken = "7.2"

[package.metadata.docs.rs]
all-features = true
